[package]
name = "mini_python"
version = "0.1.0"
authors = ["yu-i9 <yuu.igarashi.9@gmail.com>"]

[lib]
name = "core"
path = "src/core/mod.rs"

[[bin]]
name = "minpy"
path = "src/main.rs"

[dependencies]
